<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\MicroServiceSystem.Services.Identity.Application\MicroServiceSystem.Services.Identity.Application.csproj" />
    <ProjectReference Include="..\MicroServiceSystem.Services.Identity.Persistence\MicroServiceSystem.Services.Identity.Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Messaging\MicroServiceSystem.BuildingBlocks.Messaging.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Authentication\MicroServiceSystem.BuildingBlocks.Authentication.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
