<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MicroServiceSystem.Services.MsfService.Application\MicroServiceSystem.Services.MsfService.Application.csproj" />
    <ProjectReference Include="..\MicroServiceSystem.Services.MsfService.Persistence\MicroServiceSystem.Services.MsfService.Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Messaging\MicroServiceSystem.BuildingBlocks.Messaging.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Storage\MicroServiceSystem.BuildingBlocks.Storage.csproj" />
  </ItemGroup>

</Project>
