apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: msf-secrets
  namespace: msf
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: YOUR_CLUSTER_SECRET_STORE
    kind: ClusterSecretStore
  target:
    name: msf-microservice-system-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SIGNING_KEY
      remoteRef:
        key: msf/jwt-signing-key
    - secretKey: INTERNAL_API_KEY
      remoteRef:
        key: msf/internal-api-key
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: msf/rabbitmq-password
    - secretKey: IDENTITY_CONNECTION_STRING
      remoteRef:
        key: msf/cs-identity
    - secretKey: USER_CONNECTION_STRING
      remoteRef:
        key: msf/cs-user
    - secretKey: COORDINATOR_CONNECTION_STRING
      remoteRef:
        key: msf/cs-coordinator
    - secretKey: AUDIT_CONNECTION_STRING
      remoteRef:
        key: msf/cs-audit
    - secretKey: FILE_CONNECTION_STRING
      remoteRef:
        key: msf/cs-file
    - secretKey: LOCATION_CONNECTION_STRING
      remoteRef:
        key: msf/cs-location
    - secretKey: NOTIFICATION_CONNECTION_STRING
      remoteRef:
        key: msf/cs-notification
    - secretKey: SETTINGS_CONNECTION_STRING
      remoteRef:
        key: msf/cs-settings
    - secretKey: MONGO_CONNECTION_STRING
      remoteRef:
        key: msf/mongo
    - secretKey: REDIS_CONNECTION
      remoteRef:
        key: msf/redis
    - secretKey: MIGRATE_POSTGRES_PASSWORD
      remoteRef:
        key: msf/postgres-password
