<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\MicroServiceSystem.Services.Notification.Application\MicroServiceSystem.Services.Notification.Application.csproj" />
    <ProjectReference Include="..\MicroServiceSystem.Services.Notification.Infrastructure\MicroServiceSystem.Services.Notification.Infrastructure.csproj" />
    <ProjectReference Include="..\MicroServiceSystem.Services.Notification.Persistence\MicroServiceSystem.Services.Notification.Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.ServiceDefaults\MicroServiceSystem.BuildingBlocks.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
