<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\MicroServiceSystem.Services.Location.Application\MicroServiceSystem.Services.Location.Application.csproj" />
    <ProjectReference Include="..\MicroServiceSystem.Services.Location.Infrastructure\MicroServiceSystem.Services.Location.Infrastructure.csproj" />
    <ProjectReference Include="..\MicroServiceSystem.Services.Location.Persistence\MicroServiceSystem.Services.Location.Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.ServiceDefaults\MicroServiceSystem.BuildingBlocks.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
