apiVersion: v1
kind: Secret
metadata:
  name: {{ include "msf.fullname" . }}-secrets
  labels:
    {{- include "msf.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SIGNING_KEY: {{ .Values.secrets.jwtSigningKey | quote }}
  INTERNAL_API_KEY: {{ .Values.secrets.internalApiKey | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | quote }}
  IDENTITY_CONNECTION_STRING: {{ .Values.secrets.connectionStrings.identity | quote }}
  USER_CONNECTION_STRING: {{ .Values.secrets.connectionStrings.user | quote }}
  COORDINATOR_CONNECTION_STRING: {{ .Values.secrets.connectionStrings.coordinator | quote }}
  AUDIT_CONNECTION_STRING: {{ .Values.secrets.connectionStrings.audit | quote }}
  FILE_CONNECTION_STRING: {{ .Values.secrets.connectionStrings.file | quote }}
  LOCATION_CONNECTION_STRING: {{ .Values.secrets.connectionStrings.location | quote }}
  NOTIFICATION_CONNECTION_STRING: {{ .Values.secrets.connectionStrings.notification | quote }}
  SETTINGS_CONNECTION_STRING: {{ .Values.secrets.connectionStrings.settings | quote }}
  MONGO_CONNECTION_STRING: {{ .Values.infrastructure.mongoConnectionString | quote }}
  REDIS_CONNECTION: {{ .Values.infrastructure.redisConnection | quote }}
