<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\MicroServiceSystem.Services.Audit.Domain\MicroServiceSystem.Services.Audit.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Application\MicroServiceSystem.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Caching\MicroServiceSystem.BuildingBlocks.Caching.csproj" />
    <ProjectReference Include="..\..\..\Shared\Contracts\MicroServiceSystem.Contracts.csproj" />
  </ItemGroup>
</Project>
