<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\MicroServiceSystem.Services.Settings.Application\MicroServiceSystem.Services.Settings.Application.csproj" />
    <ProjectReference Include="..\MicroServiceSystem.Services.Settings.Infrastructure\MicroServiceSystem.Services.Settings.Infrastructure.csproj" />
    <ProjectReference Include="..\MicroServiceSystem.Services.Settings.Persistence\MicroServiceSystem.Services.Settings.Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.ServiceDefaults\MicroServiceSystem.BuildingBlocks.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
