apiVersion: v2
name: microservice-system
description: Kubernetes application deploy for MicroServiceSystem (gateway, admin SPA, APIs). External infra required.
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservices
  - aspnetcore
  - yarp
home: https://github.com/drnserhat/MicroServiceSystem
