<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\MicroServiceSystem.Services.Logging.Application\MicroServiceSystem.Services.Logging.Application.csproj" />
    <ProjectReference Include="..\MicroServiceSystem.Services.Logging.Infrastructure\MicroServiceSystem.Services.Logging.Infrastructure.csproj" />
    <ProjectReference Include="..\MicroServiceSystem.Services.Logging.Persistence\MicroServiceSystem.Services.Logging.Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.ServiceDefaults\MicroServiceSystem.BuildingBlocks.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
